# Generated by Django 5.1.7 on 2025-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_choice_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
