# Generated by Django 5.1.7 on 2025-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_election_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='election_photo/'),
        ),
    ]
