# Generated by Django 5.1.7 on 2025-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Серия паспорта'),
        ),
    ]
