# Generated by Django 5.1.7 on 2025-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_passport_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_series',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Passport seriyasi'),
        ),
    ]
